replicas: 3
homePage: |
    <html>
        <head>
            <title>Demo app title from values.yaml</title>
        </head>
        <body>
            <h1>Demo app from values.yaml !</h1>
        </body>
    </html>
