apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
  namespace: demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      name: demo-app
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app-nginx
          image: nginx:stable
          ports:
            - containerPort: 80
              name: http-port 
