apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo # it is unique by definition
  namespace: argocd # must match argocd namespace in use
spec:
  project: demo
  source:
    repoUrl: https://github.com/federico-paolillo/gitops-argocd-demo.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../values.yaml
    chart: demo-app  
  destination:
    namespace: demo-app
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    retry:
      limit: 3
