apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
  namespace: demo-app
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      name: demo-app
      labels:
        app: demo-app
    spec:
      volumes:
        - name: home-page
          configMap:
            name: demo-app-cm
            items:
              - key: homePage
                path: index.html
      containers:
        - name: demo-app-nginx
          image: nginx:stable
          ports:
            - containerPort: 80
              name: http-port 
          volumeMounts:
            - name: home-page
              mountPath: /usr/share/nginx/html