apiVersion: v1
kind: Service
metadata:
  name: demo-app-svc
  namespace: demo-app
spec:
  type: NodePort
  ports:
    - nodePort: {{ .Values.nodePort }} 
      targetPort: http-port
      port: 65535
  selector:
    app: demo-app